- hosts: homeassistant
  become: true
  become_user: homeassistant
  gather_facts: no
  tasks:
    - name: update pip
      pip:
        name: pip
        extra_args: --upgrade
        virtualenv: /srv/homeassistant
    - name: update homeassistant via pip
      pip:
        name: homeassistant
        extra_args: --upgrade
        virtualenv: /srv/homeassistant
    - name: update configs with latest
      git:
        repo: https://tjsimmons@bitbucket.org/tjsimmons/homeassistant-configs.git
        dest: /home/homeassistant/.homeassistant
        clone: no
        update: yes
        force: yes
    - name: restart homeassistant
      become: true
      become_user: root
      command: systemctl restart home-assistant@homeassistant
