- hosts: docker
  become_user: root
  become: true
  tasks:
    - name: install necessary packages
      apt:
        name: ["python-apt", "apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        update-cache: yes
        state: present
    - name: add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 0EBFCD88
        state: present
    - name: add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    - name: install Docker
      apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        update-cache: yes
        state: present
