- name: Install docker
  hosts: docker
  become_user: root
  become: true
  tasks:
    - name: Install necessary packages
      ansible.builtin.apt:
        name: ["python-apt", "apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        update-cache: true
        state: present
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 0EBFCD88
        state: present
    - name: Add Docker repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    - name: Install Docker
      ansible.builtin.apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        update-cache: true
        state: present
