- hosts: all
  tasks:
    - name: ensure all SSH keys are on system
      authorized_key:
        user: "{{ ansible_env.USER }}"
        state: present
        key: "{{ item }}"
      with_file: 
        - keys/yubikey5nfc
        - keys/yubikey4
        - keys/yubikey4c-1
        - keys/yubikey4c-2
        - keys/gylfaginning
    - name: update all installed packages
      become: true
      become_user: root
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
