- hosts: "{{ target }}"
  pre_tasks:
    - name: ensure aptitude is installed
      raw: apt install -y aptitude
    - name: ensure python2 is installed
      raw: apt install -y python-minimal
  tasks:
    - name: update all installed packages
      apt:
        update_cache: yes
        upgrade: yes
