- name: Install llm
  hosts: "{{ variable_host | default('llm') }}"
  # can override the host by using ansible-playbook install-llms.yml --extra-vars "variable_host={target}"
  tasks:
    - name: Change owner of /usr/share/llm to current user
      ansible.builtin.file:
        dest: /usr/share/llm
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: u+rwx
        recurse: true
      become: true
    - name: Set the git credential helper as the default, so we can store the huggingface-cli token
      community.general.git_config:
        name: credential.helper
        value: store
        scope: global
    - name: Clone text-generation-webui
      ansible.builtin.git:
        repo: https://github.com/oobabooga/text-generation-webui.git
        dest: /usr/share/llm/text-generation-webui
        clone: true
        update: false
        version: v1.5
    - name: Install text-generation-webui dependencies
      ansible.builtin.pip:
        chdir: /usr/share/llm/text-generation-webui
        virtualenv: /usr/share/llm/.venv
        extra_args: --extra-index https://download.pytorch.org/whl/nightly/cu121
        requirements: requirements.txt
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
    - name: Clone fastchat
      ansible.builtin.git:
        repo: https://github.com/lm-sys/FastChat.git
        dest: /usr/share/llm/fastchat
        clone: true
        update: false
        version: v0.2.29
    - name: Install a few fastchat requirements
      ansible.builtin.pip:
        virtualenv: /usr/share/llm/fastchat/.fastchat
        name:
          - bitsandbytes
          - scipy
    - name: Install fastchat requirements in editable
      ansible.builtin.pip:
        virtualenv: /usr/share/llm/fastchat/.fastchat
        editable: true
        name: ".[model_worker,webui]"
    - name: Make a directory for poc
      ansible.builtin.file:
        path: "/usr/share/llm/{{ item }}"
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: u+wrx,o+r
      loop:
        - poc
    - name: Install requirements for poc
      ansible.builtin.pip:
        virtualenv: /usr/share/llm/poc/.poc
        extra_args: --extra-index https://download.pytorch.org/whl/nightly/cu121
        name:
          - sentence-transformers
          - weaviate-client
          - tiktoken
          - jq
          - farm-haystack[all-gpu]
          - vllm
          - vllm-haystack
          - einops
          - chainlit
      environment:
        PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_env.USER }}/.local/bin"
    - name: Install packagecloud signing key
      ansible.builtin.get_url:
        url: https://packagecloud.io/github/git-lfs/gpgkey
        dest: /etc/apt/trusted.gpg.d/packagecloud.asc
        mode: a+rwx
        force: true
      become: true
    - name: Add packagecloud repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/packagecloud.asc] https://packagecloud.io/github/git-lfs/ubuntu/ jammy main"
        state: present
        update_cache: true
      become: true
    - name: Install git-lfs
      ansible.builtin.apt:
        name: git-lfs
        state: present
      become: true
    - name: Enable git lfs
      ansible.builtin.command:
        cmd: git lfs install
    - name: Copy weaviate dockerfile and start script
      ansible.builtin.copy:
        src: weaviate/
        dest: /usr/share/llm/weaviate/
        mode: a+rwx
